# Generated by Django 2.0.3 on 2018-03-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.PositiveIntegerField()),
                ('p2_score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('wins', models.PositiveIntegerField()),
                ('loss', models.PositiveIntegerField()),
                ('draw', models.PositiveIntegerField()),
                ('games_played', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['wins'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='p1_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='room.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='room.Player'),
        ),
    ]
