# Generated by Django 2.0.3 on 2018-03-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180330_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
