# Generated by Django 2.0.3 on 2018-04-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20180403_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-wins']},
        ),
    ]
